# Generated by Django 4.2 on 2023-05-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcgData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('qrs_duration', models.IntegerField()),
                ('p_r_interval', models.IntegerField()),
                ('q_t_interval', models.IntegerField()),
                ('t_interval', models.IntegerField()),
                ('p_interval', models.IntegerField()),
                ('qrs', models.IntegerField()),
                ('t', models.IntegerField()),
                ('p', models.IntegerField()),
                ('qrst', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('q_wave', models.FloatField()),
                ('r_wave', models.FloatField()),
                ('s_wave', models.FloatField()),
                ('diagnosis', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=80)),
            ],
        ),
    ]
